project_id = "qsedjxegavrwomflakjq"

[functions.manage-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.ai-briefing]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.approve-proposal]
verify_jwt = false

[functions.street-view]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.retrieve-session]
verify_jwt = false

[functions.patch-orphaned-projects]
verify_jwt = false
