project_id = "qsedjxegavrwomflakjq"

[functions.manage-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.ai-briefing]
verify_jwt = false

[functions.send-email]
verify_jwt = false
